Import Required Libraries

In [6]:
# Numerical computation
import numpy as np

# Data handling
import pandas as pd

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Neural Network
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

Load & Inspect Dataset

In [7]:
#Load dataset
df = pd.read_csv("weatherHistory.csv.zip")

#Display first 5 rows
df.head

<bound method NDFrame.head of                       Formatted Date        Summary Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain
...                              ...            ...         ...
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy        rain
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy        rain
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy        rain
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy        rain
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy        rain

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197
1             9.355556                  7.227778      0.86            14.2646
2             9.377778                  9.377778      0.89             3.9284
3             8.288889                  5.944444      0.83            14.1036
4             8.755556                  6.977778      0.83            11.0446
...                ...                       ...       ...                ...
96448        26.016667                 26.016667      0.43            10.9963
96449        24.583333                 24.583333      0.48            10.0947
96450        22.038889                 22.038889      0.56             8.9838
96451        21.522222                 21.522222      0.60            10.5294
96452        20.438889                 20.438889      0.61             5.8765

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0
1                       259.0          15.8263         0.0
2                       204.0          14.9569         0.0
3                       269.0          15.8263         0.0
4                       259.0          15.8263         0.0
...                       ...              ...         ...
96448                    31.0          16.1000         0.0
96449                    20.0          15.5526         0.0
96450                    30.0          16.1000         0.0
96451                    20.0          16.1000         0.0
96452                    39.0          15.5204         0.0

       Pressure (millibars)                           Daily Summary
0                   1015.13       Partly cloudy throughout the day.
1                   1015.63       Partly cloudy throughout the day.
2                   1015.94       Partly cloudy throughout the day.
3                   1016.41       Partly cloudy throughout the day.
4                   1016.51       Partly cloudy throughout the day.
...                     ...                                     ...
96448               1014.36  Partly cloudy starting in the morning.
96449               1015.16  Partly cloudy starting in the morning.
96450               1015.66  Partly cloudy starting in the morning.
96451               1015.95  Partly cloudy starting in the morning.
96452               1016.16  Partly cloudy starting in the morning.

[96453 rows x 12 columns]>

In [10]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [8]:
#Check dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [9]:
#Check missing values
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [12]:
# Create temperature categories
def classify_temp(temp):
    if temp < 15:
        return 0  # Cold
    elif temp < 25:
        return 1  # Moderate
    else:
        return 2  # Hot

# Apply classification using correct column name
df['Temp_Class'] = df['Temperature (C)'].apply(classify_temp)

# Check class distribution
df['Temp_Class'].value_counts()

Temp_Class
0    59188
1    28029
2     9236
Name: count, dtype: int64

In [13]:
# Define input features
X = df[['Humidity', 'Wind Speed (km/h)', 'Pressure (millibars)']]

# Define target
y = df['Temp_Class']

# Quick check
X.head(), y.head()

(   Humidity  Wind Speed (km/h)  Pressure (millibars)
 0      0.89            14.1197               1015.13
 1      0.86            14.2646               1015.63
 2      0.89             3.9284               1015.94
 3      0.83            14.1036               1016.41
 4      0.83            11.0446               1016.51,
 0    0
 1    0
 2    0
 3    0
 4    0
 Name: Temp_Class, dtype: int64)

In [14]:
from sklearn.model_selection import train_test_split

# Split the dataset (80% train, 20% test) with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Check dataset sizes
X_train.shape, X_test.shape

((77162, 3), (19291, 3))

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
from tensorflow.keras.utils import to_categorical

y_train_cat = to_categorical(y_train, num_classes=3)
y_test_cat = to_categorical(y_test, num_classes=3)

y_train_cat.shape

(77162, 3)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Build Neural Network model
model = Sequential()

model.add(Dense(16, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Display model summary
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 227 (908.00 B)

 Trainable params: 227 (908.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
history = model.fit(
    X_train_scaled,
    y_train_cat,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.6413 - loss: 0.7370 - val_accuracy: 0.7196 - val_loss: 0.6068
Epoch 2/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7197 - loss: 0.5977 - val_accuracy: 0.7284 - val_loss: 0.5845
Epoch 3/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7286 - loss: 0.5806 - val_accuracy: 0.7325 - val_loss: 0.5736
Epoch 4/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7328 - loss: 0.5727 - val_accuracy: 0.7354 - val_loss: 0.5656
Epoch 5/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7373 - loss: 0.5632 - val_accuracy: 0.7356 - val_loss: 0.5626
Epoch 6/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7351 - loss: 0.5626 - val_accuracy: 0.7386 - val_loss: 0.5610
Epoch 7/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7390 - loss: 0.5552 - val_accuracy: 0.7379 - val_loss: 0.5603
Epoch 8/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7391 - loss: 0.5553 - val_accuracy: 0.7379 - val_loss: 0.5585
Epoch 9/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7370 - loss: 0.5564 - val_accuracy: 0.7381 - val_loss: 0.5585
Epoch 10/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7384 - loss: 0.5575 - val_accuracy: 0.7391 - val_loss: 0.5573
Epoch 11/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7375 - loss: 0.5586 - val_accuracy: 0.7380 - val_loss: 0.5591
Epoch 12/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7399 - loss: 0.5585 - val_accuracy: 0.7376 - val_loss: 0.5582
Epoch 13/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7419 - loss: 0.5536 - val_accuracy: 0.7400 - val_loss: 0.5564
Epoch 14/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7392 - loss: 0.5545 - val_accuracy: 0.7389 - val_loss: 0.5576
Epoch 15/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7412 - loss: 0.5526 - val_accuracy: 0.7396 - val_loss: 0.5584
Epoch 16/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7380 - loss: 0.5553 - val_accuracy: 0.7376 - val_loss: 0.5575
Epoch 17/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7378 - loss: 0.5537 - val_accuracy: 0.7397 - val_loss: 0.5570
Epoch 18/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7382 - loss: 0.5552 - val_accuracy: 0.7402 - val_loss: 0.5562
Epoch 19/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7417 - loss: 0.5522 - val_accuracy: 0.7406 - val_loss: 0.5558
Epoch 20/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7400 - loss: 0.5537 - val_accuracy: 0.7389 - val_loss: 0.5554
Epoch 21/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7401 - loss: 0.5553 - val_accuracy: 0.7389 - val_loss: 0.5569
Epoch 22/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7386 - loss: 0.5555 - val_accuracy: 0.7398 - val_loss: 0.5573
Epoch 23/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7377 - loss: 0.5551 - val_accuracy: 0.7409 - val_loss: 0.5550
Epoch 24/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7370 - loss: 0.5560 - val_accuracy: 0.7402 - val_loss: 0.5552
Epoch 25/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7417 - loss: 0.5484 - val_accuracy: 0.7382 - val_loss: 0.5573
Epoch 26/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7382 - loss: 0.5527 - val_accuracy: 0.7386 - val_loss: 0.5573
Epoch 27/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7389 - loss: 0.5543 - val_accuracy: 0.7402 - val_loss: 0.5583
Epoch 28/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7388 - loss: 0.5535 - val_accuracy: 0.7411 - val_loss: 0.5551
Epoch 29/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7408 - loss: 0.5505 - val_accuracy: 0.7387 - val_loss: 0.5552
Epoch 30/30
1930/1930 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7414 - loss: 0.5507 - val_accuracy: 0.7411 - val_loss: 0.5550

In [19]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predict on test set
y_pred = model.predict(X_test_scaled)
y_pred_classes = np.argmax(y_pred, axis=1)

# Overall accuracy
print("Test Accuracy:", accuracy_score(y_test, y_pred_classes))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:\n", cm)

# Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred_classes))

603/603 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Test Accuracy: 0.7415375045357939
Confusion Matrix:
 [[10315  1426    97]
 [ 2166  2785   655]
 [   24   618  1205]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.87      0.85     11838
           1       0.58      0.50      0.53      5606
           2       0.62      0.65      0.63      1847

    accuracy                           0.74     19291
   macro avg       0.67      0.67      0.67     19291
weighted avg       0.73      0.74      0.74     19291